# Dockerfile.server for AI Client

# Use an official Python runtime as a parent image
FROM python:3.12-alpine

# Set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Install dependencies
COPY ./PongAI/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt


# Copy the application code
COPY ./PongAI /app/

# Command to start the AI client
CMD ["python", "app.py"]
