export const SELECTORS = {
    loginButton: '#login_with_42',
    qrCodePopover: '#qrcode-popover',
    accountButton: '#account_button',
    accountDropdown: '#account_dropdown',
    eraseDataButton: '#erase_data',
    eraseDataPopover: '#last-check-popover',
    logoutButton: '#logout',
    difficultyPopover: '#difficulty-popover',
    multiplayerPopover: '#multiplayer-popover',
    tournamentPopover: '#tournament-popover',
    singlePlayerButton: '#single-player-button',
    multiPlayerButton: '#multi-player-button',
    easyButton: '#easy_button',
    mediumButton: '#medium_button',
    hardButton: '#hard_button',
    sharedScreenButton: '#shared_screen_button',
    lanButton: '#lan_button',
    tournamentButton: '#tournament-button',
    mainMenu: '#main-menu',
};
